// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PaymentProvider is an autogenerated mock type for the PaymentProvider type
type PaymentProvider struct {
	mock.Mock
}

type PaymentProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentProvider) EXPECT() *PaymentProvider_Expecter {
	return &PaymentProvider_Expecter{mock: &_m.Mock}
}

// ProcessPayment provides a mock function with given fields: amount, currency
func (_m *PaymentProvider) ProcessPayment(amount float64, currency string) (string, error) {
	ret := _m.Called(amount, currency)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPayment")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(float64, string) (string, error)); ok {
		return rf(amount, currency)
	}
	if rf, ok := ret.Get(0).(func(float64, string) string); ok {
		r0 = rf(amount, currency)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(float64, string) error); ok {
		r1 = rf(amount, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentProvider_ProcessPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessPayment'
type PaymentProvider_ProcessPayment_Call struct {
	*mock.Call
}

// ProcessPayment is a helper method to define mock.On call
//   - amount float64
//   - currency string
func (_e *PaymentProvider_Expecter) ProcessPayment(amount interface{}, currency interface{}) *PaymentProvider_ProcessPayment_Call {
	return &PaymentProvider_ProcessPayment_Call{Call: _e.mock.On("ProcessPayment", amount, currency)}
}

func (_c *PaymentProvider_ProcessPayment_Call) Run(run func(amount float64, currency string)) *PaymentProvider_ProcessPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(string))
	})
	return _c
}

func (_c *PaymentProvider_ProcessPayment_Call) Return(_a0 string, _a1 error) *PaymentProvider_ProcessPayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentProvider_ProcessPayment_Call) RunAndReturn(run func(float64, string) (string, error)) *PaymentProvider_ProcessPayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentProvider creates a new instance of PaymentProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentProvider {
	mock := &PaymentProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
